db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=somepass
    - POSTGRES_USER=flyspray

web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./app/cache:/app/cache
    - ./app/attachments:/app/attachments
